spring.application.name=backend

# Menggunakan Environment Variables untuk keamanan data di GitHub
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/postgres
spring.datasource.username=postgres.pzjriukvrfqvmqxqwybk
spring.datasource.password=${DB_PASSWORD}

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
